const jsonData = [
{ category: "wildlife",
title: "Baby Whale Playing",
filename: "Baby_Whale_Playing.jpg",
camera: "PENTAX K-3 Mark III",
focal: "75.0 mm",
aperture: "5.6",
exposure: "1/2000",
iso: "400",
},
{ category: "wildlife",
title: "Bald Eagle",
filename: "Bald_Eagle.jpg",
camera: "PENTAX K-3 Mark III",
focal: "220.0 mm",
aperture: "10.0",
exposure: "1/1250",
iso: "1600",
},
{ category: "wildlife",
title: "Bear Lake",
filename: "Bear_Lake.jpg",
camera: "PENTAX K-5 II",
focal: "19.0 mm",
aperture: "20.0",
exposure: "1.3",
iso: "100",
},
{ category: "wildlife",
title: "Booted Raquet-tail Hummingbirds",
filename: "Booted_Raquet_tail_Hummingbirds.jpg",
},
{ category: "wildlife",
title: "Chestnut Breasted Hummingbird",
filename: "Chestnut_Breasted_Hummingbird.jpg",
camera: "PENTAX K-5 II",
focal: "300.0 mm",
aperture: "5.0",
exposure: "1/180",
iso: "1250",
},
{ category: "wildlife",
title: "Collared Inca Hummingbird",
filename: "Collared_Inca_Hummingbird.jpg",
camera: "PENTAX K-5 II",
focal: "300.0 mm",
aperture: "18.0",
exposure: "1/160",
iso: "250",
},
{ category: "wildlife",
title: "Grizzly feeding on salmon at Brooks Falls",
filename: "Grizzly_feeding_on_salmon_at_Brooks_Falls.jpg",
},
{ category: "wildlife",
title: "Mother and Baby Humpbacks",
filename: "Mother_and_Baby_Humpbacks.jpg",
camera: "E-M5MarkII",
focal: "12.0 mm",
aperture: "5.6",
exposure: "1/400",
iso: "400",
},
{ category: "wildlife",
title: "Orca Prince William Sound",
filename: "Orca_Prince_William_Sound.jpg",
camera: "PENTAX K-3 Mark III",
focal: "170.0 mm",
aperture: "7.1",
exposure: "1/1600",
iso: "800",
},
{ category: "wildlife",
title: "Otter Prince William Sound",
filename: "Otter_Prince_William_Sound.jpg",
camera: "PENTAX K-3 Mark III",
focal: "300.0 mm",
aperture: "14.0",
exposure: "1/1600",
iso: "1600",
},
{ category: "landscape",
title: "Oxbow Bend Grand Tetons",
filename: "Oxbow_Bend_Grand_Tetons.jpg",
camera: "PENTAX K-3 Mark III",
focal: "16.0 mm",
aperture: "6.3",
exposure: "1/320",
iso: "800",
},
{ category: "landscape",
title: "Stones of Stenness, Orkney Islands",
filename: "Stones_of_Stenness_Orkney_Islands.jpg",
},
	{ category: "wildlife",
	  filename: "Atlantic_Puffin_in_flight.jpg",
	  title: "Atlantic Puffin in flight",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "300.0 mm",
	  aperture: "5.6",
	  exposure: "1/2500",
	  iso: "3200" },
	{ category: "wildlife",
	  filename: "Atlantic_Puffins_Iceland.jpg",
	  title: "Atlantic Puffins Iceland",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "300.0 mm",
	  aperture: "5.6",
	  exposure: "1/1250",
	  iso: "1600" },
	{ category: "wildlife",
	  filename: "Bald_Eagle_at_Smith_Mountain_Lake.jpg",
	  title: "Bald Eagle at Smith Mountain Lake",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "300.0 mm",
	  aperture: "4.0",
	  exposure: "1/1250",
	  iso: "1600" },
	{ category: "wildlife",
	  filename: "Bald_Eagle_at_Smith_Mountain_Lake2.jpg",
	  title: "Bald Eagle at Smith Mountain Lake (2)",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "300.0 mm",
	  aperture: "4.0",
	  exposure: "1/1250",
	  iso: "1600" },
	{ category: "wildlife",
	  filename: "Gray_Whale_San_Ignacio_Lagoon_Baja_Mexico.jpg",
	  title: "Gray Whale San Ignacio Lagoon Baja Mexico ",
	  desc: "",
	  focal: "",
	  exposure: "",
	  iso: "" },
	{ category: "landscape",
	  filename: "Gullfoss_Iceland.jpg",
	  title: "Gullfoss Iceland.jpg",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "16.0 mm",
	  aperture: "9.0",
	  exposure: "1/1000",
	  iso: "400" },
	{ category: "wildlife",
	  filename: "Humpback_Mother_and_Baby2.jpg",
	  title: "Humpback Mother and Baby",
	  desc: "",
	  camera: "E-M5MarkII",
	  focal: "12.0 mm",
	  aperture: "5.6",
	  exposure: "1/320",
	  iso: "400" },
	{ category: "landscape",
	  filename: "Machu_Picchu.jpg",
	  title: "Machu Picchu",
	  desc: "",
	  camera: "PENTAX K-5 II",
	  focal: "16.0 mm",
	  aperture: "6.3",
	  exposure: "1/500",
	  iso: "800" },
	{ category: "wildlife",
	  filename: "Mother_and_Baby_Humpback_Whales_at_Silver_Bank.jpg",
	  title: "Mother and Baby Humpback Whales at Silver Bank",
	  desc: "",
	  focal: "",
	  aperture: "",
	  exposure: "",
	  iso: "" },
	{ category: "landscape",
	  filename: "Mount_Kirkjufell_and_Kirkjufellsfoss_Iceland.jpg",
	  title: "Mount Kirkjufell and Kirkjufellsfoss Iceland",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "17.5 mm",
	  aperture: "14.0",
	  exposure: "1/250",
	  iso: "400" },
	{ category: "landscape",
	  filename: "Seljarlandsfoss_Iceland.jpg",
	  title: "Seljarlandsfoss Iceland",
	  desc: "",
	  camera: "PENTAX K-3 Mark III",
	  focal: "16.0 mm",
	  aperture: "11.0",
	  exposure: "1/1250",
	  iso: "1600" },
	{ category: "landscape",
	  filename: "Tuscany.jpg",
	  title: "Tuscany",
	  desc: "",
	  camera: "E-M5MarkII",
	  focal: "40.0 mm",
	  aperture: "9.0",
	  exposure: "1/160",
	  iso: "400" },
	{ category: "landscape",
	  filename: "Winter_at_Smith_Mountain_Lake.jpg",
	  title: "Winter at Smith Mountain Lake",
	  desc: "",
	  camera: "iPhone 11 Pro",
	  focal: "4.2 mm",
	  aperture: "1.8",
	  exposure: "1/1900",
	  iso: "32" },
];
