const jsonData = [
{ category: "wildlife",
title: "Baby Whale Playing",
filename: "Baby_Whale_Playing.jpg",
camera: "PENTAX K-3 Mark III",
focal: "75.0 mm",
aperture: "5.6",
exposure: "1/2000",
iso: "400",
},
{ category: "wildlife",
title: "Bald Eagle",
filename: "Bald_Eagle.jpg",
camera: "PENTAX K-3 Mark III",
focal: "220.0 mm",
aperture: "10.0",
exposure: "1/1250",
iso: "1600",
},
{ category: "wildlife",
title: "Bear Lake",
filename: "Bear_Lake.jpg",
camera: "PENTAX K-5 II",
focal: "19.0 mm",
aperture: "20.0",
exposure: "1.3",
iso: "100",
},
{ category: "wildlife",
title: "Booted Raquet-tail Hummingbirds",
filename: "Booted_Raquet_tail_Hummingbirds.jpg",
},
{ category: "wildlife",
title: "Chestnut Breasted Hummingbird",
filename: "Chestnut_Breasted_Hummingbird.jpg",
camera: "PENTAX K-5 II",
focal: "300.0 mm",
aperture: "5.0",
exposure: "1/180",
iso: "1250",
},
{ category: "wildlife",
title: "Collared Inca Hummingbird",
filename: "Collared_Inca_Hummingbird.jpg",
camera: "PENTAX K-5 II",
focal: "300.0 mm",
aperture: "18.0",
exposure: "1/160",
iso: "250",
},
{ category: "wildlife",
title: "Grizzly feeding on salmon at Brooks Falls",
filename: "Grizzly_feeding_on_salmon_at_Brooks_Falls.jpg",
},
{ category: "wildlife",
title: "Mother and Baby Humpbacks",
filename: "Mother_and_Baby_Humpbacks.jpg",
camera: "E-M5MarkII",
focal: "12.0 mm",
aperture: "5.6",
exposure: "1/400",
iso: "400",
},
{ category: "wildlife",
title: "Orca Prince William Sound",
filename: "Orca_Prince_William_Sound.jpg",
camera: "PENTAX K-3 Mark III",
focal: "170.0 mm",
aperture: "7.1",
exposure: "1/1600",
iso: "800",
},
{ category: "wildlife",
title: "Otter Prince William Sound",
filename: "Otter_Prince_William_Sound.jpg",
camera: "PENTAX K-3 Mark III",
focal: "300.0 mm",
aperture: "14.0",
exposure: "1/1600",
iso: "1600",
},
{ category: "landscape",
title: "Oxbow Bend Grand Tetons",
filename: "Oxbow_Bend_Grand_Tetons.jpg",
camera: "PENTAX K-3 Mark III",
focal: "16.0 mm",
aperture: "6.3",
exposure: "1/320",
iso: "800",
},
{ category: "landscape",
title: "Stones of Stenness, Orkney Islands",
filename: "Stones_of_Stenness_Orkney_Islands.jpg",
},
];
