const jsonData = [
	{ category: "wildlife",
	  filename: "Stones_of_Stenness_Orkney_Islands.jpg",
	  title: "Stones of Stenness Orkney Islands",
	  desc: "Duis vel iaculis aliquam faucibus feugiat tempor ante fusce netus laoreet per fusce.",
	  camera: "Canon PowerShot S95",
	  focal: "22.5mm",
	  aperture: "5.6",
	  exposure: "1/1000",
	  iso: "80" },
	{ category: "wildlife",
	  filename: "Bald_Eagle.jpg",
	  title: "Bald Eagle",
	  desc: "Mi a aliquam dictum tellus mollis pellentesque aptent nullam odio, velit sem et hac lacus erat cras arcu placerat.",
	  camera: "Canon PowerShot S95",
	  focal: "22.5mm",
	  aperture: "5.6",
	  exposure: "1/1000",
	  iso: "80" },
	{ category: "landscape",
	  filename: "Oxbow_Bend_Grand_Tetons.jpg",
	  title: "Oxbow Bend Grand Tetons",
	  desc: "Lorem ipsum aliquet vivamus tempor donec quisque rutrum lorem placerat, a dui euismod turpis imperdiet integer sodales pulvinar.",
	  camera: "Canon PowerShot S95",
	  focal: "22.5mm",
	  aperture: "/5.6",
	  exposure: "1/1000",
	  iso: "80" },
];

	  